apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            value: {{ .Values.environmentVariables.APPINSIGHTS_INSTRUMENTATIONKEY }}
          - name: cosmosdbCollectionName
            value: {{ .Values.environmentVariables.cosmosdbCollectionName }}
          - name: cosmosdbDatabaseName
            value: {{ .Values.environmentVariables.cosmosdbDatabaseName }}
          - name: cosmosdbHostName
            value: {{ .Values.environmentVariables.cosmosdbHostName }}
          - name: cosmosdbMongodbConnectionString
            value: {{ .Values.environmentVariables.cosmosdbMongodbConnectionString }}
          - name: cosmosdbPassword
            value: {{ .Values.environmentVariables.cosmosdbPassword }}
        livenessProbe:
          httpGet:
            path: /api/getRegions
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3